version: '2'
services:
    db:
        image: postgres:9.5
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
        volumes:
            - pg_data:/var/lib/postgresql/data
    odoo:
        # build:
        #     context: ./data
        #     dockerfile: Dockerfile-dev-$ODOO_VERSION
        # TODO ver como hacemos par que esto se cambie desde otro lugar
        image: $ODOO_IMAGE:$ODOO_VERSION
        external_links:
            - aeroo:aeroo
        depends_on:
            - db
        ports:
            - "8069:8069"
            - "8072:8072"
        volumes:
            - ./data/custom-addons:/opt/odoo/custom-addons
            - odoo_data:/opt/odoo/data
        env_file:
            - .env
        #these extra env items are for nginx-proxy automated reverse proxy
        #we need to design an automated hostname/dns subsystem 
        environment:
            - VIRTUAL_HOST=odoo0.local
            - VIRTUAL_PORT=8069

#dependency: nginx-proxy must be running before and must create this network
networks:
  default:
    external:
      name: dockernginxadhoc_backend

volumes:
    pg_data:
    odoo_data:
